import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    // Each test submits real transactions to the local devnet and waits for
    // proofs to be generated by the local proof server. Generous timeouts.
    testTimeout: 900_000,
    hookTimeout: 900_000,
    fileParallelism: false,
    pool: 'forks',
    poolOptions: {
      forks: { singleFork: true },
    },
  },
});
